name: Production CI/CD

on:
  push:
    branches: [main]
    tags:
      - "v*"

env:
  NODE_VERSION: 20.5.x
  HUSKY: 0

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "${{ env.NODE_VERSION }}", cache: "yarn" }
      - run: yarn install
      - run: yarn tsc --build
      - run: yarn build
      - uses: actions/upload-artifact@v4
        with: { name: "build", path: "app/dist" }

  deploy:
    name: "Deploy to Production"
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: "prod"
      url: "https://stackstrumps.com"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "${{ env.NODE_VERSION }}", cache: "yarn" }
      - run: yarn install
      - uses: actions/download-artifact@v4
        with: { name: "build", path: "app/dist" }
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}"
          channelId: live
          projectId: "stacks-top-trumps"
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
